name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build JAR
      run: ./sbtx assembly
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Check if JAR is present
      run: test -f target/scala*/cloud-storage-etl-udfs-*.jar
