name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Build JAR
      run: ./sbtx assembly
    - name: Check if JAR is present
      run: test -f target/scala*/cloud-storage-etl-udfs-*.jar
    - name: Deploy JAR to releases
      uses: skx/github-action-publish-binaries@master
      with:
        args: target/scala*/cloud-storage-etl-udfs-*.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
